/* Aula LABORATORIO DE BANCO DE DADOS */
/* Dia 15/08 */

/* Usuário: laboratorio@grad
   Host: grad
   Senha: unaerp */
   
   
  /* Criando tablespace */
  CREATE TABLESPACE tbls5w_839832 DATAFILE 'C:\app\oracle\oradata\grad\datafile\ tbls5w_839832.dbf' SIZE 10M;
  
  /* Listar o nome das tablespaces de um banco de dados */
  SELECT tbls5w_839832 FROM DBA_TABLESPACE;
  
  /* Redimensionar o tamanho de um tablespace alterando o datafile */
  /* sintaxe */
  ALTER DATABASE DATAFILE 'C:\app\oracle\oradata\grad\datafile\ tbls5w_839832.dbf' RESIZE 15M;
  
  ALTER TABLESPACE "TBLS5W_839832"
	ADD DATAFILE 'C:\app\oracle\oradata\grad\datafile\tbls5w_839832aux.dbf' 
		SIZE 5M;
		
/* Modificar o nome de um tablespace */ 
/*SINTAXE*/
/* ALTER TABLESPACE "NOME_TABLESPACE"
	RENAME TO "NOVO NOME_TABLESPACE"; */
	
/*Exemplo */
ALTER TABLESPACE "TBLS5W_839832"
	RENAME TO "5W_839832";
	
/* Remover um tablespace do banco de dados */
/* SINTAXE- DROP TABLESPACE "NOME_TABLESPACE"
[INCLUDING CONTENSTS AND DATAFILES]; */

/* Criação de usuários */
/* Sintaxe- CREATE USER "nome usuario" 
	IDENTIFIED BY "SENHA"
		 DEFAULT TABLESPACE "NOME DO TABLESPACE PADRÃO"
			TEMPORARY TABLESPACE "NOME DO TABLESPACE TEMPORARIO"
				ACOUNT [LOCK | UNLOCK]
					PROFILE "NOME DO PRIFILE" [DEFAULT]
						QUOTA ON [tamanho | UNLIMITED] */
					
CREATE USER "ARTHUR VITAL" 
	IDENTIFIED BY "lr060605"
		 DEFAULT TABLESPACE "NOME DO TABLESPACE PADRÃO"
			TEMPORARY TABLESPACE "NOME DO TABLESPACE TEMPORARIO"
				ACOUNT [LOCK | UNLOCK]
					PROFILE "NOME DO PRIFILE" [DEFAULT]
						QUOTA ON [tamanho | UNLIMITED];
						

/* Aula LABORATORIO DE BANCO DE DADOS */
/* Dia 22/08 */

/* CRIAR NOVO USUARIO */ 
CREATE USER "5W_839832"
	IDENTIFIED BY "140895"
		DEFAULT TABLESPACE TBLS5W_839832 
			TEMPORARY TABLESPACE TEMP	
				PROFILE DEFAULT 
					ACCOUNT UNLOCK;
	
 /* DISC OU DISCONNECT */
 /* CONNOU CONNECT */
 
 CONN 5W_839832@GRAD;
 
 /*  ATRIBUIR DIREITOS PARA UM USUARIO */
 GRANT direito(s)/role  TO 5W_839832/ROLE [WITH OPTION ADMIN];
 
 /* RETIRAR DIREITOS DE UM USUARIO */
 REVOKE direito(s)/role  TO 5W_839832/ROLE;
 
 /* EXEMPLOS DE DIREITOS DE SISTEMA */
 CREATE TABLE
 CREATE SESSION 
 CREATE USER 
 
 /* EXEMPLOS DE DIREITOS DE OBJETOS */
 INSERT
 UPDATE
 DELETE
 
 /* ATRIBUIR DIREITOS PARA O USUARIO CRIADO */
 GRANT CREATE SESSION, SELECT ANY TABLE, CREATE TABLE, INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE TO "5W_839832";
 
 
 DBA_USERS -- TABELA DO SISTEMA QUE ARMAZENA AS INFORMAÇÕES
 
 /* CONECTAR COM O USUARIO laboratorio */
 /* CRIAR UM NOVO USURARIO COM O NOME "EX_CODIGO' */
 
 CREATE USER "EX_839832"
	IDENTIFIED BY "140895"
		DEFAULT TABLESPACE TBLS5W_839832 
			TEMPORARY TABLESPACE TEMP	
				PROFILE DEFAULT 
					ACCOUNT UNLOCK;
					
/* ALTERAR USUARIO */
ALTER USER "EX_839832"[PARÂMTRO(S)];

/* ALTERAR SENHA DO USUARIO */
ALTER USER "EX_839832" IDENTIFIED BY "060605";

/* ALTERAR O STATUS DO USUARIO (BLOQUEALO) */
ALTER USER "EX_839832" ACCOUNT LOCK;

/* EXCLUIR UM USUARIO */
DROP USER "EX_839832" [TO CASCADE]; 

DROP USER EX_839832;

/* CONECTAR COM O USUARIO 5W_839832 */
/* VERIFICAR QUAL O NOME DO USUARIO  CONECTADO */
SHOW USER;

/*CRIAÇÃO DE TABLEAS */
/* CREATE TABLE "NOME DA TABELA" (
	ATRIIBUTO1 TIPO (TAMANHO) [UNIQUE |NOT NULL],
	ATRIBUTO2 TIPO (TAMANHO),
	ATRIBUTO3 TIPO (TAMANHO),
	CONSTRAINT "NOME" [PRIMARY KEY | FOREIGN KEY | CHECK] PARAMETROS); */
	




